version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: pulumi-resource-ripe-atlas
    main: ./provider/cmd/pulumi-resource-ripe-atlas
    binary: pulumi-resource-ripe-atlas
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X github.com/supabase/pulumi-atlas/provider/version.Version={{.Version}}

archives:
  - id: pulumi-resource-ripe-atlas
    builds:
      - pulumi-resource-ripe-atlas
    name_template: "pulumi-resource-{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
